version: '3.4'

services:

  stride-db-init:
    build: ../open-bus-stride-db
    volumes:
      - "../open-bus-stride-db:/srv"

  stride-db-backup:
    build: ../open-bus-stride-db/backup
    depends_on:
      - stride-db
    command:
      - --cron
      - "* * * * *"
    environment:
      PG_BACKUP_DB: postgres
      PG_BACKUP_HOSTNAME: stride-db
      PG_BACKUP_USER: postgres
      PG_BACKUP_SCHEMA: public
      PGPASSWORD: "123456"
      PG_BACKUP_FILENAME: /var/siri-storage/stride_db.sql.gz
    volumes:
      - ".data/siri:/var/siri-storage"

  stride-db-backup-monitor:
    build: ../open-bus-stride-db/backup
    ports:
      - "8081:8081"
    depends_on:
      - stride-db-backup
    command:
      - --health-daemon
    environment:
      PG_BACKUP_FILENAME: /var/siri-storage/stride_db.sql.gz
    volumes:
      - ".data/siri:/var/siri-storage"

  stride-etl:
    build: ../open-bus-stride-etl
    volumes:
      - "../open-bus-stride-db:/srv/open-bus-stride-db"
      - "../open-bus-stride-etl:/srv/open-bus-stride-etl"

  gtfs-etl:
    build: ../open-bus-gtfs-etl
    volumes:
      - "../open-bus-stride-db:/srv/open-bus-stride-db"
      - "../open-bus-gtfs-etl:/srv/open-bus-gtfs-etl"

  siri-requester:
    build: ../open-bus-siri-requester
    volumes:
      - ".data/siri:/var/siri-storage"
      - "../open-bus-siri-requester:/srv"

  siri-requester-health:
    build: ../open-bus-siri-requester
    volumes:
      - ".data/siri:/var/siri-storage"

  siri-requester-nginx:
    build: ../open-bus-siri-requester/nginx
    volumes:
      - ".data/siri:/srv"

  siri-etl-process-new-snapshots:
    build: ../open-bus-siri-etl
    volumes:
      - ".data/siri:/var/siri-storage"
      - "../open-bus-siri-etl:/srv"

  stride-api:
    build: ../open-bus-stride-api
    volumes:
      - "../open-bus-stride-api:/srv"
