name: Agents
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: AGENTS.codex.Dockerfile
          push: true
          tags: ghcr.io/hasadna/open-bus-pipelines/agents:latest
          cache-from: type=registry,ref=ghcr.io/hasadna/open-bus-pipelines/agents:buildcache-latest
          cache-to: type=registry,ref=ghcr.io/hasadna/open-bus-pipelines/agents:buildcache-latest,mode=max
