name: CI
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_APP_IMAGE_NAME: "docker.pkg.github.com/hasadna/open-bus-pipelines/open-bus-pipelines"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u hasadna --password-stdin &&\
        if docker pull "${DOCKER_APP_IMAGE_NAME}:latest"; then
          CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME}:latest"
        else
          CACHE_FROM_ARG=""
        fi &&\
        docker build $CACHE_FROM_ARG -t app . &&\
        docker tag app "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag app "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          docker push "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          if ! git log -1 --pretty=format:"%s" | grep -- --no-deploy \
             && ! git log -1 --pretty=format:"%s" | grep '^automatic update of siri etl requirements$' \
             && ! git log -1 --pretty=format:"%s" | grep '^automatic update of gtfs etl requirements$' \
             && ! git log -1 --pretty=format:"%s" | grep '^automatic update of stride etl requirements$'
          then
            cd `mktemp -d` &&\
            echo "${HASADNA_K8S_DEPLOY_KEY}" > hasadna_k8s_deploy_key &&\
            chmod 400 hasadna_k8s_deploy_key &&\
            export GIT_SSH_COMMAND="ssh -i `pwd`/hasadna_k8s_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
            git clone git@github.com:hasadna/hasadna-k8s.git &&\
            cd hasadna-k8s &&\
            python update_yaml.py '{"openbus":{"pipelinesImage":"'"${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}"'"}}' ./values.auto-updated.yaml &&\
            git config --global user.name "Open Bus Pipelines CI" &&\
            git config --global user.email "open-bus-pipelines-ci@localhost" &&\
            git add ./values.auto-updated.yaml && git commit -m "automatic update of open bus pipelines" &&\
            git push origin master
          fi
        fi
